name: Tomcat
description: |
  (Experimental) Traefik active load balancer
version: v7.082
category: WebServer
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v0.59.0
license:
projectURL: https://github.com/rawmind0/alpine-traefik