tomcat:
  image: "tomcat:7.0.82-jre7-alpine"
  ports:
   - ${http_port}:8080
  environment:
   - RUN_COMMAND=/usr/local/tomcat/bin/catalina.sh  run
   - CATALINA_HEAP=-server -Xmx768m -Xmn100m -Xms768m